@startuml Alerts-map
hide circle
hide stereotype
hide members    
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Alerts" <<LogicalModel>> [[StructureDefinition-AlertsCz.html]]
note top #PaleTurquoise [[alerts2FHIR-cz-amb.html]]
Concept Map
endnote
' --- Profiles mapping Alerts ---
class "composition-cz-amb" <<Profile>> [[StructureDefinition-cz-composition-amb.html]]
class "allergyIntolerance-cz-amb" <<Profile>> [[StructureDefinition-cz-allergyIntolerance-amb.html]]
class "flag-cz-amb" <<Profile>> [[StructureDefinition-cz-flag-amb.html]]

' --- Realization links ---
"Alerts" <|. "composition-cz-amb"
"Alerts" <|. "allergyIntolerance-cz-amb"
"Alerts" <|. "flag-cz-amb"

' ' (volitelné – skryté vazby jen pro rozložení v diagramu)
"Alerts" -d[hidden]-> "composition-cz-amb"
"composition-cz-amb" -d[hidden]-> "allergyIntolerance-cz-amb"
"composition-cz-amb" -d[hidden]-> "flag-cz-amb"
@enduml