@startmindmap MindmapBodyCz
* Tělo dokumentu
** Dříve vyslovaná přání
** Urgentní informace
***_ Alergie a intolerance
***_ Varování
** Údaje o ambulatním kontaku
***_ Příjem
***_ Dúvod ambulantího kontaktu 
***_ Poskytovatel ambulantní služby
** Stav při přijetí 
***_ Objektivní nález
***_ Funkční Stav
** Anamnéza
***_ Osobní anamnéza
***_ Rodinná anamnéza
***_ Sociální anamnéza
***_ Abusus
** Průběh ambulantního kontaktu
***_ Diagnostický souhrn
***_ Výkony
***_ Zdravotní pomůcky a implantáty
***_ Další významná léčba
***_ Medikace
***_ Výsledky vyšetření
***_ Klinické shrnutí
** Souhrn medikace
** Doporučení
***_ Plán péče
** Přílohy
@endmindmap