Logical: LogCzEncounterCz
Id: LogInPatientEncounterCz
Title: "A.2.3 - Údaje o ambulantním kontaktu"
Description: """Ambulantní zpráva - Záznam o ambulantním kontaktu v rámci ambulantní zprávy."""

* typ 1..1 CodeableConcept "A.2.3.1 - Typ ambulantního kontaktu" """Typ ambulantního kontaktu IMP, ACUTE, NONAC"""
* poznamka 0..1 string "A.2.3.2 - Poznámka" """Poznámka k ambulantnímu kontaktu volným textem"""
* datum 1..1 dateTime "A.2.3.3 - Datum a čas vyšetření" """Datum a čas vyšetření"""
* prijem 1..1 Base "A.2.3.4 - Příjem" """Informace o příjmu"""
  * urgentni 0..1 CodeableConcept "A.2.3.4.1 - Urgentnost ambulantního kontaktu" """Akutní nebo plánovaný"""
  * lekarId 0..1 Identifier "A.2.3.4.2 - Doporučující lékař - Id" """Identifikátor odesílajícího lékaře dle NRZP"""
  * lekarJmeno 0..1 HumanName "A.2.3.4.3 - Doporučující lékař - jméno" """Jméno a příjmení odesílajícího lékaře"""
  * doporucilOrganizaceId 0..1 Identifier "A.2.3.4.4 - Doporučující zařízení" """Id, název poskytovatele a kontaktní informace"""
* duvodPrijeti 1..1 Base "A.2.3.5 - Důvod ambulantního kontaktu" """Důvod ambulantního kontaktu"""
  * kod 0..* CodeableConcept "A.2.3.5.1 - Důvod ambulantního kontaktu - kód" """Důvod ambulantního kontaktu textem a/nebo kódem problému, nálezu či procedury"""
  * komentar 0..1 string "A.2.3.5.2 - Důvod ambulantního kontaktu - komentář" """Komentář k důvodu ambulantního kontaktu"""
* poskytovatel 0..* Base "A.2.3.6 - Poskytovatel ambulantní služby" """Identifikaci zdravotnického pracoviště, na kterém byla ambulantní služba poskytnuta"""
  * od 1..1 dateTime "A.2.3.6.1 - od do" """Období pobytu na oddělení"""
  * id 0..1 Identifier "A.2.3.6.2 - Identifikátor" """Úplný kód pracoviště/oddělení dle NRPZS"""
  * nazev 1..1 string "A.2.3.6.3 - Název" """Název oddělení"""
  * kontakt 1..* Base "A.2.3.6.4 - Kontakty" """Adresa a telekomunikační kontakty"""
