Logical: LogEnEncounterSummaryCz
Id: EncounterSummaryCz
Title: "A.2.7 - Encounter Summary"
Description: """Encounter Summary"""

* diagnosticSummary 1..* Base "A.2.7.1 - Diagnostický souhrn" """Seznam diagnóz, příznaků a problémů relevantních pro daný ambulantní kontakt. Popisuje problémy aktivní v průběhu kontaktu nebo významné pro další péči; může být kódován i textově."""
* problemDescription 1..1 string "A.2.7.1.1 - Popis problému" """Popis problému textem"""
* diagnosticSummary.problemDetails 0..1 CodeableConcept "A.2.7.1.2 - Kód" """Formalizované vyjádření zdravotního problému kódem (např. MKN-10, MKN-O)."""
* diagnosticSummary.onsetDate 0..1 dateTime "A.2.7.1.3 - Datum vzniku" """Datum vzniku onemocnění nebo příznaku, pokud je známo."""
* diagnosticSummary.resolutionDate 0..1 dateTime "A.2.7.1.4 - Datum vyřešení či remise" """Datum remise nebo zlepšení, pokud je relevantní."""
* diagnosticSummary.resolutionContext 0..1 string "A.2.7.1.5 - Okolnosti vyřešení" """Důvod změny stavu problému na neaktivní (např. provedený výkon)."""
* diagnosticSummary.severity 0..1 CodeableConcept "A.2.7.1.6 - Závažnost" """Subjektivní hodnocení závažnosti stavu klinikem (např. h7:condition-severity)."""
* diagnosticSummary.stage 0..* CodeableConcept "A.2.7.1.7 - Stadium onemocnění" """Stadium nebo grading problému podle zvolené klasifikace (např. TNM)."""
* significantProcedures 1..* Base "A.2.7.2 - Výkony" """Diagnostické a terapeutické výkony provedené v průběhu ambulantního kontaktu."""
* significantProcedures.procedureCode 0..* CodeableConcept "A.2.7.2.1 - Kód výkonu" """Kód výkonu ve vybraném kódovém systému (SNOMED CT, ICHI apod.)."""
* significantProcedures.procedureDescription 0..1 string "A.2.7.2.2 - Popis procedury" """Popis výkonu volným textem."""
* significantProcedures.bodySite 0..1 CodeableConcept "A.2.7.2.3 - Lokalizace" """Anatomická lokalizace výkonu pomocí řízené terminologie."""
* significantProcedures.performedDate 1..1 dateTime "A.2.7.2.4 - Datum provedení" """Datum provedení výkonu"""
* significantProcedures.reasonPerformed 0..1 CodeableConcept "A.2.7.2.5 - Důvod provedení" """Důvod provedení výkonu textem nebo kódem (např. MKN-10)."""
* significantProcedures.outcome 0..1 CodeableConcept "A.2.7.2.6 - Výsledek" """Formalizované vyjádření výsledku výkonu (procedure-outcome)."""
* significantProcedures.complication 0..* CodeableConcept "A.2.7.2.7 - Komplikace" """Komplikace spojené s výkonem."""
* significantProcedures.targetDevice 0..* Base "A.2.7.2.8 - Cílový zdravotnický prostředek" """Odkaz na zdravotnický prostředek implantovaný nebo jinak využitý během výkonu."""
* medicalDevices 0..* Base "A.2.7.3 - Zdravotní pomůcky a implantáty" """Zavedené nebo použité zdravotní pomůcky relevantní pro ambulantní kontakt."""
* medicalDevices.description 1..1 CodeableConcept "A.2.7.3.1 - Popis zdravotnického prostředku" """Popis zdravotnického prostředku (implantovaného či externího) textem a/nebo kódem."""
* medicalDevices.deviceIdentifier 0..1 Identifier "A.2.7.3.2 - Identifikátor prostředku" """Normalizovaný identifikátor, např. UDI."""
* medicalDevices.insertionDate 0..1 dateTime "A.2.7.3.3 - Datum zavedení" """Datum zavedení nebo první evidence prostředku relevantní pro kontakt."""
* medicalDevices.removalDate 0..1 dateTime "A.2.7.3.4 - Datum odstranění" """Datum odstranění nebo ukončení užívání prostředku, pokud se vztahuje."""
* medicalDevices.reasonForUse 0..1 CodeableConcept "A.2.7.3.5 - Důvod použití" """Klinický důvod zavedení či použití zdravotnického prostředku."""
// * dalsiVyznamnaLecba 0..* Base "A.2.7.4 - Další významná léčba" """Významné léčebné postupy, které nejsou klasifikovány jako standardní ambulantní výkony (např. chemoterapie, infuzní terapie apod.)."""
//   * popisProcedury 1..1 string "A.2.7.4.1 - Popis procedury" """Popis léčebné procedury volným textem."""
//   * lokalizace 0..1 CodeableConcept "A.2.7.4.2 - Lokalizace" """Anatomická lokalizace, je-li relevantní."""
//   * datumProvedeni 1..1 dateTime "A.2.7.4.3 - Datum provedení" """Datum provedení léčebné procedury"""
//   * duvodProvedeni 0..1 CodeableConcept "A.2.7.4.4 - Důvod provedení" """Důvod provedení léčebné procedury textem nebo kódem"""
* pharmacotherapy 0..* Base "A.2.7.5 - Medikace" """Vybraná medikamentózní léčba v průběhu ambulantního kontaktu nebo předepsaná při jeho ukončení."""
* pharmacotherapy.reason 0..1 CodeableConcept "A.2.7.5.1 - Indikace" """Důvod podání/indikační důvod medikace (text nebo odkaz na problém)."""
* pharmacotherapy.productCode 0..1 string "A.2.7.5.2 - Kód SUKL" """Kód léčiva dle databáze SÚKL, pokud je k dispozici."""
* pharmacotherapy.productName 0..1 string "A.2.7.5.3 - Název léčivého přípravku" """Registrovaný název léčiva."""
* pharmacotherapy.activeIngredient 0..* CodeableConcept "A.2.7.5.4 - Aktivní látky" """Seznam aktivních látek (název a/nebo kód ATC/IDMP)."""
* pharmacotherapy.strength 0..* Quantity "A.2.7.5.5 - Síla" """Síla aktivní látky v přípravku (vyjádřeno v jednotkách)."""
* pharmacotherapy.doseForm 0..1 CodeableConcept "A.2.7.5.6 - Forma léčiva" """Léková forma (např. tableta, sirup)."""
* pharmacotherapy.dosingInstructions 0..* string "A.2.7.5.7 - Dávkování" """Frekvence a počet jednotek podání volným textem nebo formalizovaně."""
* pharmacotherapy.route 0..1 CodeableConcept "A.2.7.5.8 - Cesta podání" """Cesta podání (např. per os, i.v.)."""
* pharmacotherapy.period 0..1 Period "A.2.7.5.9 - Období podávání" """Časový interval, kdy byla medikace podávána nebo je indikována."""
* significantResults 0..* string "A.2.7.6 Výsledky vyšetření" """Významné výsledky funkčních, diagnostických a zobrazovacích vyšetření, provedených během hospitalizace. Výsledky s nezpracovaným stavem („registered“) mají být uvedeny odděleně."""
* significantResults.date 1..1 dateTime "A.2.7.6.1 - Date" """Date and time of the observation"""
* significantResults.status 1..1 CodeableConcept "A.2.7.6.2 - Observation status" """Status of the observation (e.g. registered, preliminary, final)"""
* significantResults.description 0..1 string "A.2.7.6.3 - Result description" """Narrative representation of the observation result and findings."""
* significantResults.details 1..1 Base "A.2.7.6.4 - Observation details" """Observation details include code that identifies observation, specification of the observed body structure or specimen, date and time of the specimen collection, observation method or protocol used and other aspects of the observation."""
* significantResults.result 0..1 Base "A.2.7.6.5 - Observation result" """Result of the observation including numeric and coded results of the measurement, details about how the tests were done to get the result values, information about reference ranges and result interpretation. Content of the observation result will vary according to the type of the observation."""
* significantResults.reporter 0..* Base "A.2.7.6.7 - Reporter" """With certain observation results, e.g. there may also be an interpreter or a person responsible for validation."""

* synthesis 1..1 Base "A.2.7.7 Klinické shrnutí" """Podrobný popis důvodu a průběhu hospitalizace jako celku. Může být zakončeno klinickou úvahou (dif. dg., vysvětlení souvislostí) v klinicky složitých případech."""
* synthesis.summaryProblem 1..* Base "A.2.7.7.1 Klinický souhrn problému" """Souhrnný popis důvodu a průběhu ambulantního kontaktu za konkrétní problém."""
* synthesis.problemDescription 1..1 string "A.2.7.7.1.1 Popis problému" """Popis problému textem."""
* synthesis.reasonAndProgress 1..1 string "A.2.7.7.1.2 Důvod a průběh ambulantního kontaktu" """Podrobný popis důvodu a průběhu ambulantního kontaktu za celý pobyt."""
* synthesis.clinicalThoughts 0..1 string "A.2.7.7.2 Klinická úvaha" """Zakončení klinického shrnutí klinickou úvahou (diferenciální diagnostika, vysvětlení složitých stavů apod.)."""